name: your_app_name
description: Your app description

# These versions are examples, you might need to adjust based on your existing dependencies
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  
  # UI
  table_calendar: ^3.0.9
  
  # Permission handling
  permission_handler: ^11.0.0
  
  # Device info (needed for Android SDK version check)
  device_info_plus: ^9.0.3
  
  # Other dependencies
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  # Add any assets, fonts, etc. here
